#!/usr/bin/env bash
# Deploys the Confidential Containers (CoCo) operator and Trustee KBS on
# the current kubectl context, wiring up the "kata-qemu-coco-dev" runtime
# class so pods can opt into attested key release (Layer 3).
#
# This wraps the general public CoCo install flow. Exact manifest paths
# and kustomize overlays move between CoCo/Trustee releases, so treat this
# as a starting point: pin OPERATOR_REF/TRUSTEE_REF to versions you've
# validated, and check `kubectl get pods -A` / operator logs if a step
# doesn't behave as expected on your cluster. Upstream docs:
#   https://github.com/confidential-containers/operator
#   https://github.com/confidential-containers/trustee
set -euo pipefail

cd "$(dirname "$0")/.."

OPERATOR_REF="${OPERATOR_REF:-main}"
TRUSTEE_REF="${TRUSTEE_REF:-main}"
NAMESPACE="${NAMESPACE:-confidential-containers-system}"
KBS_ADMIN_KEY="${KBS_ADMIN_KEY:-kbs/kbs-admin.key}"

command -v kubectl >/dev/null 2>&1 || { echo "error: kubectl not found on PATH" >&2; exit 1; }
command -v git >/dev/null 2>&1 || { echo "error: git not found on PATH" >&2; exit 1; }

echo "== 1/5: cert-manager (CoCo operator dependency) =="
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.yaml
kubectl wait --for=condition=Available --timeout=300s -n cert-manager deployment --all

echo "== 2/5: CoCo operator (ref=$OPERATOR_REF) =="
kubectl apply -k "github.com/confidential-containers/operator/config/default?ref=${OPERATOR_REF}"
kubectl wait --for=condition=Available --timeout=300s -n "$NAMESPACE" deployment --all

echo "== 3/5: label nodes as CoCo/Kata install targets =="
# The operator only installs onto nodes matching its ccNodeSelector, which
# defaults to node.kubernetes.io/worker="" when unset. Real multi-node
# clusters are generally expected to have already labeled their worker
# nodes with this (it's not something kubeadm sets automatically); single
# -node dev clusters (kind/minikube) almost certainly haven't. Label every
# node here — a no-op on nodes that already carry the label, required for
# the CcRuntime install to find any node at all otherwise (it fails with
# "no suitable worker nodes found").
for node in $(kubectl get nodes -o jsonpath='{.items[*].metadata.name}'); do
  kubectl label node "$node" node.kubernetes.io/worker= --overwrite
done

echo "== 4/5: ccruntime CR selecting the kata-qemu-coco-dev runtime class =="
# Applied from the operator's own sample overlay (same ref as the operator
# above) rather than a hand-written CR: the CcRuntime CRD schema has moved
# between operator releases (e.g. spec.ccRuntimeConfig was flattened into
# spec.config, and runtimeClasses entries now require a `pulltype` field),
# so tracking upstream's own sample keeps this in sync automatically.
kubectl apply -k "github.com/confidential-containers/operator/config/samples/ccruntime/default?ref=${OPERATOR_REF}"

echo "waiting for the kata-qemu-coco-dev RuntimeClass to appear ..."
for _ in $(seq 1 30); do
  kubectl get runtimeclass kata-qemu-coco-dev >/dev/null 2>&1 && break
  sleep 10
done
kubectl get runtimeclass kata-qemu-coco-dev

echo "== 5/5: Trustee KBS (ref=$TRUSTEE_REF), sample/dev deployment =="
# The upstream kustomize base's secretGenerator needs a local kbs.pem (the
# KBS admin authentication public key) that isn't part of the trustee
# repo — it's meant to be generated by the deployer, and kustomize can't
# inject a local file into a bare github.com?ref= overlay. So clone the
# ref locally, drop our public key into the base dir, and apply from that
# local path instead.
if [[ ! -f "$KBS_ADMIN_KEY" ]]; then
  echo "generating KBS admin Ed25519 keypair at $KBS_ADMIN_KEY"
  mkdir -p "$(dirname "$KBS_ADMIN_KEY")"
  openssl genpkey -algorithm ed25519 -out "$KBS_ADMIN_KEY"
fi

TRUSTEE_CHECKOUT="$(mktemp -d)"
trap 'rm -rf "$TRUSTEE_CHECKOUT"' EXIT
git init -q "$TRUSTEE_CHECKOUT"
git -C "$TRUSTEE_CHECKOUT" fetch -q --depth 1 https://github.com/confidential-containers/trustee.git "$TRUSTEE_REF"
git -C "$TRUSTEE_CHECKOUT" checkout -q FETCH_HEAD
openssl pkey -in "$KBS_ADMIN_KEY" -pubout -out "$TRUSTEE_CHECKOUT/kbs/config/kubernetes/base/kbs.pem"

kubectl apply -k "$TRUSTEE_CHECKOUT/kbs/config/kubernetes/base"
# The base kustomization pins its own namespace (coco-tenant as of
# ref=main); read it back instead of hardcoding it here.
KBS_NAMESPACE="$(grep -m1 '^namespace:' "$TRUSTEE_CHECKOUT/kbs/config/kubernetes/base/kustomization.yaml" | awk '{print $2}')"
KBS_NAMESPACE="${KBS_NAMESPACE:-coco-tenant}"
kubectl wait --for=condition=Available --timeout=300s -n "$KBS_NAMESPACE" deployment/kbs || true

cat <<EOF

Next steps:
  1. Generate an admin token JWT signed with $KBS_ADMIN_KEY:
       scripts/generate_kbs_admin_token.sh $KBS_ADMIN_KEY kbs/admin-token
  2. Note the KBS Service's cluster address, e.g.
     http://kbs.${KBS_NAMESPACE}.svc.cluster.local:8080 (or
     'kubectl port-forward -n ${KBS_NAMESPACE} svc/kbs 8080:8080' for
     local access), and export it as KBS_URL for
     scripts/set_kbs_resource_policy.sh / scripts/push_key_to_kbs.sh.
  3. Run scripts/set_kbs_resource_policy.sh, then scripts/push_key_to_kbs.sh
     (both also need KBS_ADMIN_TOKEN_FILE=kbs/admin-token from step 1).
  4. Point k8s/consumer-pod-coco.yaml's
     io.katacontainers.config.agent.aa_kbc_params annotation at that same
     KBS_URL before applying it.
EOF
